/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ccipLocalSimulatorSol from "./CCIPLocalSimulator.sol";
export type { ccipLocalSimulatorSol };
