/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from "./test";
export { CrossChainNameServiceLookup__factory } from "./CrossChainNameServiceLookup__factory";
export { CrossChainNameServiceReceiver__factory } from "./CrossChainNameServiceReceiver__factory";
export { CrossChainNameServiceRegister__factory } from "./CrossChainNameServiceRegister__factory";
export { ICrossChainNameServiceLookup__factory } from "./ICrossChainNameServiceLookup__factory";
